name: GitVersion - PR

env:
  GITVERSION_VERSION: 6.3.0

on:
  pull_request:
    types: [opened, synchronize, reopened]    
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      gitversion_semver: ${{ steps.gitversion_step.outputs.SemVer }}
      gitversion_majorminorpatch: ${{ steps.gitversion_step.outputs.MajorMinorPatch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.0.1
        with:
          versionSpec: ${{ env.GITVERSION_VERSION }}

      - name: Execute GitVersion
        id: gitversion_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v4.0.1
      
  build:
    runs-on: ubuntu-latest
    needs: [ setup ]
    env:
      gitversion_semver: ${{ needs.setup.outputs.gitversion_semver }}
      gitversion_majorminorpatch: ${{ needs.setup.outputs.gitversion_majorminorpatch }}
    steps:
      - name: Use job variables (pwsh - outputs without prefix)
        shell: pwsh
        run: |
          echo "SemVer            : $env:gitversion_semver"
          echo "MajorMinorPatch   : $env:gitversion_majorminorpatch"

      - name: Use local env mapped from output (pwsh - outputs without prefix)
        shell: pwsh
        env:
          gitversion_semver_local: ${{ needs.setup.outputs.gitversion_semver }}
          gitversion_majorminorpatch_local: ${{ needs.setup.outputs.gitversion_majorminorpatch }}
        run: |
          echo "SemVer            : $env:gitversion_semver_local"
          echo "MajorMinorPatch   : $env:gitversion_majorminorpatch_local"
        
      - name: Use local env mapped from output (pwsh - outputs without prefix)
        shell: pwsh
        env:
          gitversion_semver_local: ${{ env.gitversion_semver }}
          gitversion_majorminorpatch_local: ${{ env.gitversion_majorminorpatch }}
        run: |
          echo "SemVer            : $env:gitversion_semver_local"
          echo "MajorMinorPatch   : $env:gitversion_majorminorpatch_local"

      - name: Use direct output from previous job (pwsh - outputs without prefix)
        shell: bash
        run: |
          echo "SemVer            : $gitversion_semver"
          echo "MajorMinorPatch   : $gitversion_majorminorpatch"
                